# Generated by Django 2.1.3 on 2018-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_created=True, verbose_name='发表的时间')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
    ]
