# Generated by Django 2.1.3 on 2018-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.IntegerField(primary_key='id', serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
