# Generated by Django 2.1.3 on 2018-12-05 16:07

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
